<a href="https://colab.research.google.com/github/sowmya1577/ML-AP23110011364/blob/main/Lab1_AP23110011364_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [ ]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [ ]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


[1 2 3]
[0.  0.2 0.4 0.6 0.8 1. ]
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
dtypes: int32 float64


In [ ]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones
narr = np.zeros((10,10),dtype=np.int32)
narr[1::2,::2] = 1
narr[::2,1::2] = 1
print(narr)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [ ]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [ ]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
arr = np.zeros((1000, 1000), dtype=np.float64)
print(arr.nbytes, "bytes")

8000000 bytes


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [ ]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [ ]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
a = a[[4, 1, 2, 3, 0], :]
print(a)



[[21 22 23 24 25]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [ ]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [ ]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
arr=np.arange(24).reshape(2,3,4)
r=arr.ravel()
f=arr.flatten()
r[0]=100
f[0]=200
print(arr)

[[[100   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [ ]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


union [1 2 3 4 5 6]
intersect [1 2]
sorted descending [6 5 4 3 2 1]


In [ ]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
import numpy as np
x_split, y_split = np.array_split(xy, 2)
print(x_split)
print(y_split)

[1 3 5]
[2 4 6]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [ ]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
vectorised addition [10 11 12 13 14]


In [ ]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.
degrees = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(degrees)
sin_values = np.sin(radians)
print(degrees)
print(radians)
print(sin_values)

[ 0 30 45 60 90]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [ ]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [40]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.
row = np.arange(1, 11)
col = np.arange(1, 11).reshape(10, 1)
table = row * col
print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [ ]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]


In [ ]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.
p = np.percentile(data, [25, 50, 75])
print(p)

[30.  58.5 75. ]


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [ ]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735] [31 49 39 40 38]


In [41]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
rng = np.random.default_rng()
rolls = rng.integers(1, 7, size=100)
proportion_sixes = np.mean(rolls == 6)

print("Proportion of 6s:", proportion_sixes)

Proportion of 6s: 0.1


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [ ]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [ ]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
from numpy.lib import recfunctions as rfn
heights = [160.0, 175.0]
pplwithht = rfn.append_fields(
    people,
    'height',
    heights,
    dtypes='f4',
    usemask=False
)
print(pplwithht)


[('Alice', 25, 55. , 160.) ('Bob', 30, 85.5, 175.)]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [ ]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [42]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
eigenvalues, _ = np.linalg.eig(A)
print('eigenvalues:', eigenvalues)


eigenvalues: [-0.35367135  0.98956315  0.28387445]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [ ]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


loaded equals A? True


In [ ]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.
np.savetxt('data.csv', data, delimiter=',', fmt='%d')
load_data = np.loadtxt('data.csv', delimiter=',')
print(data)
print(load_data.astype(int))
print(np.array_equal(data, load_data.astype(int)))

[[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
[[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
True


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [ ]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days


In [43]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
mondays = dates[dates.astype('datetime64[W]') == dates]
print(len(mondays))

13


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [44]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


2.3333333333333335


In [ ]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
arr2d = np.array([
    [1,  2, np.nan],
    [4, np.nan, 6],
    [7,  8,  9]
])
col_means = np.nanmean(arr2d, axis=0)
nan_mask = np.isnan(arr2d)
arr2d[nan_mask] = np.take(col_means, np.where(nan_mask)[1])
print("Filled array:\n", arr2d)



Filled array:
 [[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [ ]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


columns: ('date', 'step_count', 'mood', 'calories_burned', 'hours_of_sleep', 'bool_of_active', 'weight_kg') rows: 96


In [ ]:
# 🖊️ TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.
def to_iso(date_str):
    d, m, y = date_str.split('-')
    return f"{y}-{m.zfill(2)}-{d.zfill(2)}"

dates_str = fitness['date'].astype(str)
dates_iso = np.array([to_iso(d) for d in dates_str], dtype='datetime64[D]')

year_month = np.array([str(d)[:7] for d in dates_iso])
unique_months = np.unique(year_month)
monthly_steps = [fitness['step_count'][year_month == m].sum() for m in unique_months]

print("\nMonthly Step Count:")
for m, s in zip(unique_months, monthly_steps):
    print(f"{m}: {s}")

sleep = fitness['hours_of_sleep'].astype(float)
mood = fitness['mood'].astype(float)
corr = np.corrcoef(sleep, mood)[0, 1]
print("\nSleep vs Mood Correlation:", corr)

week_str = np.array([str(d.astype('datetime64[W]')) for d in dates_iso])
unique_weeks = np.unique(week_str)

print("\nWeekly Summary:")
for w in unique_weeks:
    mask = (week_str == w)
    avg_steps = fitness['step_count'][mask].mean()
    avg_sleep = sleep[mask].mean()
    avg_mood = mood[mask].mean()
    print(f"{w}: steps={avg_steps:.1f}, sleep={avg_sleep:.1f}, mood={avg_mood:.1f}")


Monthly Step Count:
2017-10: 79051
2017-11: 103071
2017-12: 89565
2018-01: 10163

Sleep vs Mood Correlation: 0.2104166644730015

Weekly Summary:
2017-10-05: steps=4741.8, sleep=5.5, mood=133.3
2017-10-12: steps=2779.4, sleep=6.1, mood=128.6
2017-10-19: steps=2789.1, sleep=5.7, mood=142.9
2017-10-26: steps=2293.6, sleep=6.1, mood=242.9
2017-11-02: steps=3568.1, sleep=3.9, mood=285.7
2017-11-09: steps=3954.0, sleep=5.9, mood=300.0
2017-11-16: steps=2910.7, sleep=5.4, mood=285.7
2017-11-23: steps=3142.6, sleep=6.1, mood=257.1
2017-11-30: steps=2913.3, sleep=7.0, mood=300.0
2017-12-07: steps=3213.4, sleep=4.1, mood=157.1
2017-12-14: steps=3204.0, sleep=4.4, mood=185.7
2017-12-21: steps=2743.3, sleep=4.4, mood=157.1
2017-12-28: steps=1857.1, sleep=3.6, mood=171.4
2018-01-04: steps=969.7, sleep=4.7, mood=200.0


## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*